covid19-miyazaki/covid19

README.md

closed #1 置換：東京都→宮崎県

---

.github/workflows/deploy.yml
.github/workflows/develop.yml
.github/workflows/staging.yml

- close #3
- #2 
- developmentブランチを更新すると、https://dev-covid19-miyazaki.netlify.com にデプロイされるようにしました。
- stagingブランチを更新すると、https://stg-covid19-miyazaki.netlify.com にデプロイされるようにしました。

closed #3 CI/CD環境の整備

---

nuxt-i18n.config.ts

- close #18 
- 多言語メニューの選択肢を制限(日本語，英語，やさしい日本語)
- xxx

多言語メニューを制限

---

README.md

- close #35 
- README.mdのリンクを東京仕様から宮崎仕様にした。

closed #35 READMEのリンクを修正

---

nuxt.config.ts

OGP画像のリンク書き換え

---

nuxt.config.ts
pages/worker.vue

- close #52
- 「企業の皆様・はたらく皆様へ」を宮崎仕様にした。

closed #52「企業の皆様・はたらく皆様へ」を宮崎仕様にした

---

README.md

- close #58 
- 翻訳者向け情報を削除
- ブランチルールを変更

closed #58

---

docs/en/README.md

- close #70 
- 英語版README.mdでogp.pngを表示

Closed: #70 英語版README.mdでogp画像が表示されていない

---

data/news.json

- close #88 
- 最新のお知らせの日付を修正しました

Closed: #88 最新のお知らせの日付修正

---

assets/locales/en.json
assets/locales/ja.json
components/SideNavigation.vue

Reverts covid19-miyazaki/covid19#96
ビルド失敗してました。マージしてすみません
https://github.com/covid19-miyazaki/covid19/actions/runs/71053171

Revert "✨ feat(URI): 宮崎県公式サイトにおける英語版ページのリンク先変更"

---

data/news.json

- close #113 
- [新型コロナウイルス感染症患者（第1例目）の発生について（続報）](https://www.pref.miyazaki.lg.jp/kohosenryaku/kenko/hoken/covid19_20200304.html)を追加しました

Closed: #113 最新のお知らせの更新(4/7)

---

.github/workflows/news_scraping.yml

- close #134 
- close #0
- #134 
お知らせの自動更新プルリクエストを作成する際、`auto_merge ` ラベルをつけることで [auto_merge_bot](https://github.com/apps/auto-merge-bot) が自動マージするようにしました
- 毎回誰かがレビューしてマージする手間が省けます

お知らせの自動更新プルリクエストを自動マージにする

---

components/SideNavigation.vue

- close #159 
- 県知事からのメッセージのリンクを更新しました

Closed: #159 知事からのメッセージのリンクを更新(4/11)

---

pages/contacts.vue
pages/parent.vue

- close #164 
-  臨時休校についてのリンクを[最新情報](https://www.pref.miyazaki.lg.jp/ky-somu/kurashi/kyoiku/20200417174606.html)に変更しました
- xxx

Closed: #164 臨時休校についてのリンクを新しい物に変更

---

.github/workflows/scraping.yml

- close #153 
- なし
- 陽性患者数のスクレイピング頻度を1時間毎->12時間毎に変更
- `scraping.yml`の`cron`を`0 */12 * * *`に修正
- なし

Closed: #153 陽性患者数のスクレイピング頻度を12時間毎に修正

---

.github/workflows/deploy.yml

- close #169
- なし
- 誤った変更をrevertで取り消した

Closed: #169 masterへの変更を取り消す

---

components/DataTable.vue

- close #176 
- もともと td タグだったのがどこかのタイミングで th に書き換えられていた
- td に戻しました
before | after
---- | ----

Fix #176 「公表日」列のデザインが変わってしまっているのを修正

---

components/TimeBarChart.vue

- close #183 
- グラフ描画に使用している Chart.js の設定を変更しました
直交座標系 · Chart.js 日本語ドキュメント https://misc.0o0o.org/chartjs-doc-ja/axes/cartesian/
before | after
---- | ----

Fix #183 陽性患者数グラフにおける最新日の棒グラフが半分途欠けているのを修正

---

.github/workflows/scraping.yml

- close #181 
- `scraping.yml`に自動でマージするようにラベルを追加
- 具体的には，`auto_merge`ラベルを追加

Closed: #181 自動でマージするようにラベルを追加

---

.github/workflows/news_scraping.yml
.github/workflows/scraping.yml

- close #194 
- プルリクエストの発行をbotユーザが行うように、`create-pull-request.token`にbotユーザのパーソナルアクセストークンを設定した。
- 本リポジトリのsecretsにBOT_TOKENを設定。
- 検査者数の更新頻度を12時間から6時間に変更。
- [別リポジトリ](https://github.com/korosuke613/experiment-trigger-problem/pull/17)で実験したので、うまく動くかと思いますが、実際に動かしてみないとわかりません....

closed #194 自動生成したプルリクエストでテストが走るようにした

---

README.md
assets/locales/en.json
assets/locales/ja.json
nuxt.config.ts
package.json

- close #253
- サイドバーに非公式の文言を追加(ja, en)
- タイトルに非公式の文言を追加
- README.mdなどに非公式の文言を追加

closed #253 非公式の文言追記

---

components/SideNavigation.vue
data/news.json
pages/index.vue

- close #251 
- 最新のお知らせを更新
- サイドバーの知事からのお知らせのリンクを更新

Closed: #251 最新のお知らせの4月分を削除しても良いのではないでしょうか？
